---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
 	metadata:
  name: podinfo-bad-kustomization
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo-deploy

