---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo-ssh-deleted
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./
  prune: false
  sourceRef:
    kind: GitRepository
    name: podinfo-ssh-deleted

